name: Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore NotificationBrokerService/NotificationBrokerService.sln

      - name: Build
        run: dotnet build NotificationBrokerService/NotificationBrokerService.sln --no-restore --configuration Release

      - name: Log in to Docker Hub
        if: success()
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        if: success()
        working-directory: NotificationBrokerService/NotificationBrokerService
        run: |
          docker build -t lucashemcph/soft1exam_notificationservice:latest .

      - name: Push Docker image
        if: success()
        run: |
          docker push lucashemcph/soft1exam_notificationservice:latest
